
all:
	snapcraft --destructive-mode --enable-experimental-target-arch --target-arch=arm64

#prepare:
#	sudo apt install gcc-aarch64-linux-gnu

#alsa-lib:
#	snapcraft build alsa-lib --destructive-mode --enable-experimental-target-arch --target-arch=arm64

#alsa-utils:
#	snapcraft build alsa-utils --destructive-mode --enable-experimental-target-arch --target-arch=arm64

clean:
	snapcraft clean --destructive-mode
