name: alsa-utils
version: 1.2.4-j-17
summary: Utilities for configuring and using ALSA
description: |
    This package contains various tools to configure audio devices via ALSA
    ALSA is the Advanced Linux Sound Architecture.

    The source can be found at: https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/alsa-utils/
confinement: strict
base: core20
grade: stable
architectures:
  - build-on: [amd64]
    run-on: arm64


apps:
    alsa-restore:
        daemon: simple
        command: bin/alsa-stated
        plugs: [alsa, device-conf]
    speaker-test:
        command: usr/bin/speaker-test
        plugs: [ alsa, home ]
    alsactl:
        command: usr/sbin/alsactl
        plugs: [ alsa, home ]
    amixer:
        command: usr/bin/amixer
        plugs: [ alsa, home ]
    aplay:
        command: usr/bin/aplay
        plugs: [ alsa, home ]
    aseqnet:
        command: usr/bin/aseqnet
        plugs: [ alsa, home ]
    alsatplg:
        command: usr/bin/alsatplg
        plugs: [ alsa, home ]
    arecordmidi:
        command: usr/bin/arecordmidi
        plugs: [ alsa, home ]
    amidi:
        command: usr/bin/amidi
        plugs: [ alsa, home ]
    alsaucm:
        command: usr/bin/alsaucm
        plugs: [ alsa, home ]
    aconnect:
        command: usr/bin/aconnect
        plugs: [ alsa, home ]
    iecset:
        command: usr/bin/iecset
        plugs: [ alsa, home ]
    alsabat:
        command: usr/bin/alsabat
        plugs: [ alsa, home ]
    aseqdump:
        command: usr/bin/aseqdump
        plugs: [ alsa, home ]
    aplaymidi:
        command: usr/bin/aplaymidi
        plugs: [ alsa, home ]
    arecord:
        command: usr/bin/arecord
        plugs: [ alsa, home ]

plugs:
    device-conf:
        interface: content
        content: alsa-conf
        target: var/lib/alsa
layout:
    /usr/share/alsa:
        symlink: $SNAP/usr/share/alsa

parts:
    alsa-lib:
        plugin: autotools
        source: ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.2.4.tar.bz2
        autotools-configure-parameters:
            - --prefix=/usr
            - --sysconfdir=/etc
            - --libexec=/usr/lib
            - --libdir=/usr/lib
            - --localstatedir=/var
            - --with-configdir=/usr/share/alsa
            - --with-plugindir=/usr/lib/alsa-lib
            - --build x86_64-pc-linux-gnu
            - --host aarch64-linux-gnu

    alsa-utils:
        after: [ alsa-lib ]
        plugin: autotools
        build-environment:
            - CFLAGS: "-I$SNAPCRAFT_PROJECT_DIR/parts/alsa-lib/install/usr/include"
            - LDFLAGS: "-L$SNAPCRAFT_PROJECT_DIR/parts/alsa-lib/install/usr//lib"
        source: ftp://ftp.alsa-project.org/pub/utils/alsa-utils-1.2.4.tar.bz2
        autotools-configure-parameters:
            - --prefix=/usr
            - --sysconfdir=/etc
            - --libexec=/usr/lib
            - --libdir=/usr/lib
            - --localstatedir=/var
            - --build x86_64-pc-linux-gnu
            - --host aarch64-linux-gnu
            - --disable-alsamixer
            - --disable-alsaloop

    alsa-stated:
        plugin: dump
        source: bin
        organize:
            alsa-stated: bin/
