name: dbus-c # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: SERVER SIDE D-Bus application # 79 char long summary
description: |
  POC to demostrate a D-Bus application.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

plugs:
  dbus-slot:
    interface: dbus
    bus: session
    name: com.honeywell.cam

apps:
  dbus-c:
    command: dbus_c
    plugs: [ dbus-slot ]

parts:
  dbus-c:
    plugin: make
    source: src
    build-packages: [libdbus-1-dev]    
