name: rc
version: '1.4'
confinement: strict
summary: Demo teh usage of daemon in snap
description: |
  Please find the source of this snap at:
  https://github.com/snapcore/snapd/tree/master/tests/lib/snaps/test-snapd-service

grade: stable
base: core20

slots:
    shared-execute-slot:
        interface: content
        content: mybin
        read:
            - $SNAP/bin

plugs:
    shared-execute-plug:
        interface: content
        content: mybin
        target: $SNAP/extra-bin


apps:
    hello:
        command: bin/hello
        slots: [shared-execute-slot]
    rc:
        command: bin/rc
        daemon: simple
        plugs:
            - hardware-observe
            - shared-execute-plug


parts:
    common:
        after: [ lspci ]
        plugin: make
        source: src
        build-packages:
            - libudev-dev
        make-parameters:
            - DNS=no
            - SHARED=yes
            - CFLAGS=-I$SNAPCRAFT_PROJECT_DIR/parts/lspci/build
            - LDFLAGS="-L$SNAPCRAFT_PROJECT_DIR/parts/lspci/build/lib -lpci -ludev -lresolv"
    lspci:
        plugin: make
        source: https://github.com/pciutils/pciutils.git







