name: test-snapd-audio-record
version: "1"
summary: test-snapd-audio-record snap
description:
  test-snapd-audio-record
confinement: strict
base: core20
grade: devel
architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

environment:
  LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

apps:
  play:
    command: bin/pawrap $SNAP/usr/bin/paplay
    plugs:
    - audio-playback
    - home
  record:
    command: bin/pawrap $SNAP/usr/bin/parecord
    plugs:
    - audio-playback
    - audio-record
    - home
  recsimple:
    command: bin/pawrap $SNAP/bin/parec-simple
    plugs:
    - audio-playback
    - audio-record
    - home
  pactl:
    command: bin/pawrap $SNAP/usr/bin/pactl
    plugs:
    - audio-playback
    - home

parts:
  pawrap:
    plugin: dump
    source: files/
  parec-simple:
    plugin: make
    source: .
    build-packages:
    - libc6-dev
    - libpulse-dev
    - gcc
  pulse-utils:
    plugin: nil
    override-build: |
      snapcraftctl build
      rm -f $SNAPCRAFT_PART_INSTALL/usr/bin/paplay $SNAPCRAFT_PART_INSTALL/usr/bin/parecord
      cp -f $SNAPCRAFT_PART_INSTALL/usr/bin/pacat $SNAPCRAFT_PART_INSTALL/usr/bin/paplay
      cp -f $SNAPCRAFT_PART_INSTALL/usr/bin/pacat $SNAPCRAFT_PART_INSTALL/usr/bin/parecord
    stage-packages:
      - pulseaudio
      - pulseaudio-utils
      - libsndfile1
      - libxcb1
      - libasyncns0
      - libflac8
      - libvorbisenc2
      - libxau6
      - libxdmcp6
      - libogg0
      - libvorbis0a
      # Needed for the example .wav files for testing purposes
      - alsa-utils
    prime:
      - usr/bin/paplay
      - usr/bin/parecord
      - usr/bin/pactl
      - usr/lib/*/pulseaudio/libpulsecommon-*.so*
      - usr/share/sounds/alsa/Noise.wav
      - usr/lib/*/libpulse.so*
      - usr/lib/*/libpulse-simple.so*
      - usr/lib/*/libsndfile.so*
      - usr/lib/*/libxcb.so*
      - usr/lib/*/libasyncns.so*
      - usr/lib/*/libFLAC.so*
      - usr/lib/*/libvorbisenc.so*
      - usr/lib/*/libXau.so*
      - usr/lib/*/libXdmcp.so*
      - usr/lib/*/libogg.so*
      - usr/lib/*/libvorbis.so.*
