name: test-snapd-service
version: '1.0'
confinement: strict
summary: Demo teh usage of daemon in snap
description: |
  Please find the source of this snap at:
  https://github.com/snapcore/snapd/tree/master/tests/lib/snaps/test-snapd-service

grade: stable
base: core20

slots:
    shared-content-slot:
        interface: content
        content: mybin
        read:
            - $SNAP/bin

plugs:
    shared-content-plug:
        interface: content
        content: mybin
        target: $SNAP/extra-bin


apps:
    test-snapd-service:
        command: bin/start
        stop-command: bin/stop
        daemon: simple
        reload-command: bin/reload
    test-snapd-other-service:
        command: bin/start-other
        daemon: simple
    test-snapd-sighup-service:
        command: bin/start-stop-mode sighup
        stop-command: bin/stop-stop-mode sighup
        daemon: simple
        stop-mode: sighup
    test-snapd-sighup-all-service:
        command: bin/start-stop-mode sighup-all
        stop-command: bin/stop-stop-mode sighup-all
        daemon: simple
        stop-mode: sighup-all
    test-snapd-sigusr1-service:
        command: bin/start-stop-mode sigusr1
        stop-command: bin/stop-stop-mode sigusr1
        daemon: simple
        stop-mode: sigusr1
    test-snapd-sigusr1-all-service:
        command: bin/start-stop-mode sigusr1-all
        stop-command: bin/stop-stop-mode sigusr1-all
        daemon: simple
        stop-mode: sigusr1-all
    test-snapd-sigusr2-service:
        command: bin/start-stop-mode sigusr2
        stop-command: bin/stop-stop-mode sigusr2
        daemon: simple
        stop-mode: sigusr2
    test-snapd-sigusr2-all-service:
        command: bin/start-stop-mode sigusr2-all
        stop-command: bin/stop-stop-mode sigusr2-all
        daemon: simple
        stop-mode: sigusr2-all
    test-snapd-sigterm-service:
        command: bin/start-stop-mode-sigterm
        daemon: simple
        stop-mode: sigterm
    test-snapd-sigterm-all-service:
        command: bin/start-stop-mode-sigterm
        daemon: simple
        stop-mode: sigterm-all
    test-snapd-endure-service:
        command: bin/start-stop-mode endure
        stop-command: bin/stop-stop-mode endure
        daemon: simple
        refresh-mode: endure
    test-snapd-service-refuses-to-stop:
        command: bin/start
        daemon: simple
        stop-command: bin/stop 60
        stop-timeout: 10s
    hello:
        command: bin/hello
        slots: [shared-content-slot]
    test-hello:
        command: bin/test-hello
        daemon: simple
        plugs: [shared-content-plug]

parts:
    common:
        plugin: dump
        source: .
        stage: [bin]
    hello:
        plugin: make
        source: src/hello




